# Generated by Django 6.0 on 2025-12-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
